Support standalone mode rule configuration
integrated-application-development/delphilint pull request #37
Opened 2024-05-16 06:13 UTC by fourls

This PR adds a new user-level configuration setting to configure which rules are applied in standalone mode:

![image](https://github.com/integrated-application-development/delphilint/assets/28214458/75dcdef0-6ff5-4ba1-b80c-878e4893dd55)

By default, DelphiLint is configured to use SonarDelphi's default ruleset (the Sonar way profile), preserving existing behaviour. Users can opt-in to configure their own ruleset, at which point they can enable or disable which rules they like. Under the hood, only *disabled* rules are stored, meaning that any new rules that appear as a result of a SonarDelphi upgrade will be automatically upgraded.

As tends to happen with these sorts of paradigm-shift changes, this PR also includes a few collateral improvements:

* Some Sonar issues have been fixed
* The settings form has been redesigned as a tabbed view
* SonarDelphi version configuration now only queries GitHub when a new "Edit" button is clicked, rather than upon form show
* SonarDelphi version configuration now queries GitHub in a background thread
* Rule retrieval in Standalone Mode now includes security hotspots and excludes template rules
* The `SonarHostTokens` settings item is no longer capped at 2048 characters

2024-05-17 00:21 UTC, fourls commented
Implemented compatibility with the new features in the VS Code companion - while you can't customise the rules from within VSCode, it will honour the disabled rules configuration.

2024-05-23 08:45 UTC, Cirras requested changes
Great bit of work here, love the new settings panel.
A few minor comments, but overall code looks good. I'll be doing some additional user testing as well before approving.

2024-05-23 08:45 UTC, Cirras commented on client/source/DelphiLint.SettingsFrame.pas
> +    EnableAll1: TMenuItem;
Can we rename it to `EnableAll` so that we don't have this stray `1` in the field and method name?

2024-05-23 08:45 UTC, Cirras commented on client/source/DelphiLint.SettingsFrame.pas
> +    DisableAll1: TMenuItem;
Can we rename it to `DisableAll` so that we don't have this stray `1` in the field and method name?

2024-05-23 08:45 UTC, Cirras commented on client/source/DelphiLint.SettingsFrame.pas
> +
Stray new lines here.

2024-05-24 04:18 UTC, Cirras approved these changes
🎉

2024-05-24 04:23 UTC, merged