Add note about precompiled BPM
integrated-application-development/delphilint pull request #52
Opened 2024-06-26 12:38 UTC by denieu

Adds note about possible problems in precompiled BPLs, as reported in the issue #51.

I'm not sure which version the Delphi 12 Athens BPL is compiled in, but I'll adjust it after the review if necessary.

2024-06-26 14:25 UTC, fourls commented
Hi @denieu,

I'm wondering if it might be better to add a message like this at the bottom of each release, since it may change between releases. I could do that fairly easily without needing a code change.

I guess we could still include a brief disclaimer in the README, just saying something like "Please note that there may be some compatibility issues when installing the precompiled packages on a different version than they were compiled for."

What do you think?

2024-06-26 19:37 UTC, denieu commented
I think it's great, this way we prevent the README from becoming outdated when the compiler used changes.

2024-06-26 23:35 UTC, fourls requested changes
Looks good for the most part - I've just made a couple of suggestions to make it more concise and stand out more on the page.

2024-06-26 23:35 UTC, fourls commented on README.md
> +The precompiled BPLs available in [the latest release](https://github.com/integrated-application-development/delphilint/releases/latest) were compiled in specific versions of Delphi, using them in di
```suggestion
> [!NOTE]
> Using the precompiled BPLs in different minor versions from which they were compiled can cause compatibility problems in some circumstances. If you encounter issues, please [build from source](#building-from-source).
```

2024-06-28 02:44 UTC, fourls approved these changes
Thanks @denieu, looks good.

I'll update the releases soon.

2024-06-28 02:44 UTC, merged